### ISSUE TITLE
安装会报错

### ISSUE THREAD

**Issue by cheanss** [MyFaith/Proxies#1]
Python版本：3.4
Win10
使用`pip install proxies`命令安装的时候会报以下错误：
`UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 48: illegal multibyte sequence`

**Comment by cheanss** [comment]
找到解决办法了，但只能用于git clone下载源码的方式安装
源码下载后，将README.rst文件里面中文都换成英文就可以了。

**Comment by MyFaith** [comment]
感谢反馈
